<#
.SYNOPSIS
    Configures comprehensive Windows audit policies for security monitoring.

.DESCRIPTION
    This script configures Windows Advanced Audit Policies aligned with:
    - Microsoft Security Compliance Toolkit recommendations
    - CIS Benchmarks for Windows
    - MITRE ATT&CK detection coverage requirements

    Supports Windows Server 2016/2019/2022 and Windows 10/11.

.PARAMETER LogPath
    Path to store the audit policy configuration backup and logs.
    Default: C:\SecurityBaseline\Logs

.PARAMETER BackupExisting
    Creates a backup of existing audit policies before applying changes.
    Default: $true

.PARAMETER WhatIf
    Shows what would be changed without making actual changes.

.PARAMETER SysmonInstalled
    Skip Process Creation/Termination policies if Sysmon is installed.
    Sysmon Event 1/5 are superior to Windows Event 4688/4689.
    Default: $false

.EXAMPLE
    .\windows-audit-policy.ps1

.EXAMPLE
    .\windows-audit-policy.ps1 -SysmonInstalled
    # Skips Process Creation/Termination (Sysmon provides better coverage)

.EXAMPLE
    .\windows-audit-policy.ps1 -LogPath "D:\Logs\AuditPolicy" -Verbose

.NOTES
    Author: Security Engineering Team
    Version: 2.1.0
    Last Updated: 2024-12-29

    MULTI-LANGUAGE SUPPORT:
    This script uses subcategory GUIDs instead of names, which ensures
    compatibility with ALL Windows language versions (English, Italian,
    German, French, Spanish, etc.)

    SECURITY CONSIDERATIONS:
    - Run with administrative privileges
    - Review audit volume impact on disk space
    - Configure event log retention accordingly
    - Consider central log collection (WEF/SIEM)

    OWASP/CIS REFERENCES:
    - CIS Microsoft Windows Server 2022 Benchmark v2.0.0
    - Microsoft Security Compliance Toolkit
#>

[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [Parameter()]
    [string]$LogPath = "C:\SecurityBaseline\Logs",

    [Parameter()]
    [bool]$BackupExisting = $true,

    [Parameter()]
    [switch]$RestoreDefaults,

    [Parameter()]
    [switch]$SysmonInstalled  # Skip Process Creation/Termination if Sysmon is active (avoids duplicates)
)

#Requires -RunAsAdministrator
#Requires -Version 5.1

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ============================================================================
# CRITICAL SECURITY EVENTS REFERENCE
# ============================================================================
# The following Windows Security Event IDs are generated by this audit policy:
#
#   | Event ID | Descrizione                  | Criticità  | Policy Source                    |
#   |----------|------------------------------|------------|----------------------------------|
#   | 4625     | Failed Logon (Brute Force)   | 🔴 CRITICO | Logon                            |
#   | 4771     | Kerberos Pre-Auth Failed     | 🔴 CRITICO | Kerberos Authentication Service  |
#   | 4776     | NTLM Auth Failed             | 🔴 CRITICO | Credential Validation            |
#   | 4720     | User Account Created         | 🔴 CRITICO | User Account Management          |
#   | 4722     | User Account Enabled         | 🟠 ALTO    | User Account Management          |
#   | 4724     | Password Reset Attempt       | 🟠 ALTO    | User Account Management          |
#   | 4728     | User Added to Security Group | 🔴 CRITICO | Security Group Management        |
#   | 4732     | User Added to Local Admin    | 🔴 CRITICO | Security Group Management        |
#   | 4672     | Special Privileges Assigned  | 🟠 ALTO    | Special Logon                    |
#   | 4648     | Explicit Credentials Used    | 🟠 ALTO    | Logon                            |
#   | 4688     | Process Creation             | ⚠️ SKIP*   | Process Creation                 |
#   | 4689     | Process Termination          | ⚠️ SKIP*   | Process Termination              |
#   * SKIP if Sysmon installed: Sysmon Event 1/5 are SUPERIOR (include hash, parent process)
#   | 4697     | Service Installed            | 🔴 CRITICO | Security System Extension        |
#   | 4698     | Scheduled Task Created       | 🔴 CRITICO | Object Access (Other)            |
#   | 4768     | Kerberos TGT Request         | 🟠 ALTO    | Kerberos Authentication Service  |
#   | 4769     | Kerberos Service Ticket      | 🟠 ALTO    | Kerberos Service Ticket Ops      |
#   | 4770     | Kerberos Ticket Renewed      | 🟢 MEDIO   | Kerberos Service Ticket Ops      |
#   | 5140     | Network Share Accessed       | 🟠 ALTO    | File Share                       |
#   | 5145     | Network Share Object Access  | 🟠 ALTO    | Detailed File Share              |
#   | 5156     | WFP Connection Allowed       | 🟢 MEDIO   | Filtering Platform Connection    |
#   | 5157     | WFP Connection Blocked       | 🟠 ALTO    | Filtering Platform Connection    |
#
# ============================================================================

# ============================================================================
# CONFIGURATION
# ============================================================================

# ============================================================================
# SUBCATEGORY GUIDs (Language-Independent)
# These GUIDs work on ALL Windows languages (English, Italian, German, etc.)
# Reference: Microsoft Security Audit Policy Settings
# ============================================================================
$Script:SubcategoryGUIDs = @{
    # Account Logon
    "Credential Validation"              = "{0CCE923F-69AE-11D9-BED3-505054503030}"
    "Kerberos Authentication Service"    = "{0CCE9242-69AE-11D9-BED3-505054503030}"
    "Kerberos Service Ticket Operations" = "{0CCE9240-69AE-11D9-BED3-505054503030}"
    "Other Account Logon Events"         = "{0CCE9241-69AE-11D9-BED3-505054503030}"

    # Account Management
    "Application Group Management"       = "{0CCE9239-69AE-11D9-BED3-505054503030}"
    "Computer Account Management"        = "{0CCE9236-69AE-11D9-BED3-505054503030}"
    "Distribution Group Management"      = "{0CCE9238-69AE-11D9-BED3-505054503030}"
    "Other Account Management Events"    = "{0CCE923A-69AE-11D9-BED3-505054503030}"
    "Security Group Management"          = "{0CCE9237-69AE-11D9-BED3-505054503030}"
    "User Account Management"            = "{0CCE9235-69AE-11D9-BED3-505054503030}"

    # Detailed Tracking
    "DPAPI Activity"                     = "{0CCE922D-69AE-11D9-BED3-505054503030}"
    "PNP Activity"                       = "{0CCE9248-69AE-11D9-BED3-505054503030}"
    "Process Creation"                   = "{0CCE922B-69AE-11D9-BED3-505054503030}"
    "Process Termination"                = "{0CCE922C-69AE-11D9-BED3-505054503030}"
    "RPC Events"                         = "{0CCE922E-69AE-11D9-BED3-505054503030}"
    "Token Right Adjusted Events"        = "{0CCE924A-69AE-11D9-BED3-505054503030}"

    # DS Access
    "Detailed Directory Service Replication" = "{0CCE923E-69AE-11D9-BED3-505054503030}"
    "Directory Service Access"           = "{0CCE923B-69AE-11D9-BED3-505054503030}"
    "Directory Service Changes"          = "{0CCE923C-69AE-11D9-BED3-505054503030}"
    "Directory Service Replication"      = "{0CCE923D-69AE-11D9-BED3-505054503030}"

    # Logon/Logoff
    "Account Lockout"                    = "{0CCE9217-69AE-11D9-BED3-505054503030}"
    "Group Membership"                   = "{0CCE9249-69AE-11D9-BED3-505054503030}"
    "IPsec Extended Mode"                = "{0CCE921A-69AE-11D9-BED3-505054503030}"
    "IPsec Main Mode"                    = "{0CCE9218-69AE-11D9-BED3-505054503030}"
    "IPsec Quick Mode"                   = "{0CCE9219-69AE-11D9-BED3-505054503030}"
    "Logoff"                             = "{0CCE9216-69AE-11D9-BED3-505054503030}"
    "Logon"                              = "{0CCE9215-69AE-11D9-BED3-505054503030}"
    "Network Policy Server"              = "{0CCE9243-69AE-11D9-BED3-505054503030}"
    "Other Logon/Logoff Events"          = "{0CCE921C-69AE-11D9-BED3-505054503030}"
    "Special Logon"                      = "{0CCE921B-69AE-11D9-BED3-505054503030}"
    "User / Device Claims"               = "{0CCE9247-69AE-11D9-BED3-505054503030}"

    # Object Access
    "Application Generated"              = "{0CCE9222-69AE-11D9-BED3-505054503030}"
    "Certification Services"             = "{0CCE9221-69AE-11D9-BED3-505054503030}"
    "Central Policy Staging"             = "{0CCE9246-69AE-11D9-BED3-505054503030}"
    "Detailed File Share"                = "{0CCE9244-69AE-11D9-BED3-505054503030}"
    "File Share"                         = "{0CCE9224-69AE-11D9-BED3-505054503030}"
    "File System"                        = "{0CCE921D-69AE-11D9-BED3-505054503030}"
    "Filtering Platform Connection"      = "{0CCE9226-69AE-11D9-BED3-505054503030}"
    "Filtering Platform Packet Drop"     = "{0CCE9225-69AE-11D9-BED3-505054503030}"
    "Handle Manipulation"                = "{0CCE9223-69AE-11D9-BED3-505054503030}"
    "Kernel Object"                      = "{0CCE921F-69AE-11D9-BED3-505054503030}"
    "Other Object Access Events"         = "{0CCE9227-69AE-11D9-BED3-505054503030}"
    "Registry"                           = "{0CCE921E-69AE-11D9-BED3-505054503030}"
    "Removable Storage"                  = "{0CCE9245-69AE-11D9-BED3-505054503030}"
    "SAM"                                = "{0CCE9220-69AE-11D9-BED3-505054503030}"

    # Policy Change
    "Audit Policy Change"                = "{0CCE922F-69AE-11D9-BED3-505054503030}"
    "Authentication Policy Change"       = "{0CCE9230-69AE-11D9-BED3-505054503030}"
    "Authorization Policy Change"        = "{0CCE9231-69AE-11D9-BED3-505054503030}"
    "Filtering Platform Policy Change"   = "{0CCE9233-69AE-11D9-BED3-505054503030}"
    "MPSSVC Rule-Level Policy Change"    = "{0CCE9232-69AE-11D9-BED3-505054503030}"
    "Other Policy Change Events"         = "{0CCE9234-69AE-11D9-BED3-505054503030}"

    # Privilege Use
    "Non Sensitive Privilege Use"        = "{0CCE9229-69AE-11D9-BED3-505054503030}"
    "Other Privilege Use Events"         = "{0CCE922A-69AE-11D9-BED3-505054503030}"
    "Sensitive Privilege Use"            = "{0CCE9228-69AE-11D9-BED3-505054503030}"

    # System
    "IPsec Driver"                       = "{0CCE9213-69AE-11D9-BED3-505054503030}"
    "Other System Events"                = "{0CCE9214-69AE-11D9-BED3-505054503030}"
    "Security State Change"              = "{0CCE9210-69AE-11D9-BED3-505054503030}"
    "Security System Extension"          = "{0CCE9211-69AE-11D9-BED3-505054503030}"
    "System Integrity"                   = "{0CCE9212-69AE-11D9-BED3-505054503030}"
}

$Script:AuditPolicies = @{
    # ==========================================================================
    # ACCOUNT LOGON CATEGORY
    # Monitors authentication and credential validation
    # MITRE: T1078 (Valid Accounts), T1110 (Brute Force)
    # ==========================================================================
    "Credential Validation" = @{
        Success = $true
        Failure = $true
        Description = "Tracks credential validation against SAM/AD. Critical for detecting brute force and credential stuffing."
        MITRE = "T1110, T1078"
    }
    "Kerberos Authentication Service" = @{
        Success = $true
        Failure = $true
        Description = "Tracks Kerberos TGT requests. Essential for Golden Ticket and Pass-the-Hash detection."
        MITRE = "T1558.001, T1550.003"
    }
    "Kerberos Service Ticket Operations" = @{
        Success = $true
        Failure = $true
        Description = "Tracks Kerberos service ticket requests. Critical for Kerberoasting detection."
        MITRE = "T1558.003"
    }
    "Other Account Logon Events" = @{
        Success = $true
        Failure = $true
        Description = "Catch-all for other authentication events."
        MITRE = "T1078"
    }

    # ==========================================================================
    # ACCOUNT MANAGEMENT CATEGORY
    # Monitors user, group, and computer account changes
    # MITRE: T1136 (Create Account), T1098 (Account Manipulation)
    # ==========================================================================
    "Application Group Management" = @{
        Success = $true
        Failure = $true
        Description = "Tracks application-specific group modifications."
        MITRE = "T1098"
    }
    "Computer Account Management" = @{
        Success = $true
        Failure = $true
        Description = "Tracks computer account creation/modification. Critical for detecting rogue DCs."
        MITRE = "T1136.002"
    }
    "Distribution Group Management" = @{
        Success = $true
        Failure = $true
        Description = "Tracks distribution group changes."
        MITRE = "T1098"
    }
    "Other Account Management Events" = @{
        Success = $true
        Failure = $true
        Description = "Catch-all for account management events."
        MITRE = "T1098"
    }
    "Security Group Management" = @{
        Success = $true
        Failure = $true
        Description = "Tracks security group membership changes. CRITICAL for privilege escalation detection."
        MITRE = "T1098, T1078"
    }
    "User Account Management" = @{
        Success = $true
        Failure = $true
        Description = "Tracks user account creation, modification, deletion. CRITICAL for persistence detection."
        MITRE = "T1136.001, T1098"
    }

    # ==========================================================================
    # DETAILED TRACKING CATEGORY
    # Process and DLL activity tracking
    # MITRE: T1059 (Command and Scripting Interpreter)
    # ==========================================================================
    "DPAPI Activity" = @{
        Success = $true
        Failure = $true
        Description = "Tracks Data Protection API usage for credential access attempts."
        MITRE = "T1555"
    }
    "PNP Activity" = @{
        Success = $true
        Failure = $false
        Description = "Tracks Plug and Play device events for USB monitoring."
        MITRE = "T1052.001"
    }
    # ⚠️ OVERLAP WARNING: If Sysmon is installed, these are DUPLICATES
    # Sysmon Event 1 (ProcessCreate) is SUPERIOR to Windows Event 4688:
    #   - Includes file hash (SHA256)
    #   - Includes parent process details
    #   - Includes full command line by default
    # Use -SysmonInstalled parameter to skip these policies
    "Process Creation" = @{
        Success = $true
        Failure = $false
        Description = "Tracks process creation. SKIP if Sysmon installed (Event 1 is superior)."
        MITRE = "T1059, T1204"
        SkipIfSysmon = $true  # Flag for conditional application
    }
    "Process Termination" = @{
        Success = $true
        Failure = $false
        Description = "Tracks process termination. SKIP if Sysmon installed (Event 5 is superior)."
        MITRE = "T1562.001"
        SkipIfSysmon = $true  # Flag for conditional application
    }
    "RPC Events" = @{
        Success = $true
        Failure = $true
        Description = "Tracks RPC activity for lateral movement detection."
        MITRE = "T1021"
    }
    "Token Right Adjusted Events" = @{
        Success = $true
        Failure = $false
        Description = "Tracks token privilege adjustments for privilege escalation detection."
        MITRE = "T1134"
    }

    # ==========================================================================
    # DS ACCESS CATEGORY (Domain Controllers Only)
    # Active Directory access monitoring
    # MITRE: T1003.006 (DCSync), T1484 (Domain Policy Modification)
    # ==========================================================================
    "Detailed Directory Service Replication" = @{
        Success = $true
        Failure = $true
        Description = "CRITICAL for DC: Detects DCSync attacks."
        MITRE = "T1003.006"
    }
    "Directory Service Access" = @{
        Success = $true
        Failure = $true
        Description = "Tracks AD object access for reconnaissance detection."
        MITRE = "T1087.002"
    }
    "Directory Service Changes" = @{
        Success = $true
        Failure = $true
        Description = "Tracks AD object modifications for persistence detection."
        MITRE = "T1484"
    }
    "Directory Service Replication" = @{
        Success = $true
        Failure = $true
        Description = "Tracks normal replication events."
        MITRE = "T1003.006"
    }

    # ==========================================================================
    # LOGON/LOGOFF CATEGORY
    # Session tracking for lateral movement detection
    # MITRE: T1021 (Remote Services)
    # ==========================================================================
    "Account Lockout" = @{
        Success = $false
        Failure = $true
        Description = "Tracks account lockouts for brute force detection."
        MITRE = "T1110"
    }
    "Group Membership" = @{
        Success = $true
        Failure = $false
        Description = "Logs group membership at logon time."
        MITRE = "T1078"
    }
    "IPsec Extended Mode" = @{
        Success = $false
        Failure = $false
        Description = "IPsec authentication events. Usually disabled."
        MITRE = "N/A"
    }
    "IPsec Main Mode" = @{
        Success = $false
        Failure = $false
        Description = "IPsec authentication events. Usually disabled."
        MITRE = "N/A"
    }
    "IPsec Quick Mode" = @{
        Success = $false
        Failure = $false
        Description = "IPsec authentication events. Usually disabled."
        MITRE = "N/A"
    }
    "Logoff" = @{
        Success = $true
        Failure = $false
        Description = "Tracks user logoff events for session duration analysis."
        MITRE = "T1078"
    }
    "Logon" = @{
        Success = $true
        Failure = $true
        Description = "CRITICAL: Tracks all logon attempts. Essential for lateral movement detection."
        MITRE = "T1021, T1078"
    }
    "Network Policy Server" = @{
        Success = $true
        Failure = $true
        Description = "NPS/RADIUS authentication events."
        MITRE = "T1021"
    }
    "Other Logon/Logoff Events" = @{
        Success = $true
        Failure = $true
        Description = "Catch-all for logon events."
        MITRE = "T1078"
    }
    "Special Logon" = @{
        Success = $true
        Failure = $false
        Description = "Tracks privileged logons (administrator, service accounts)."
        MITRE = "T1078.002"
    }
    "User / Device Claims" = @{
        Success = $true
        Failure = $false
        Description = "Dynamic access control claims."
        MITRE = "T1078"
    }

    # ==========================================================================
    # OBJECT ACCESS CATEGORY
    # File, registry, and object access monitoring
    # MITRE: T1083 (File Discovery), T1012 (Query Registry)
    # ==========================================================================
    "Application Generated" = @{
        Success = $true
        Failure = $true
        Description = "Application-specific audit events."
        MITRE = "T1106"
    }
    "Certification Services" = @{
        Success = $true
        Failure = $true
        Description = "CRITICAL: Certificate authority operations. Detects AD CS attacks."
        MITRE = "T1649"
    }
    "Central Policy Staging" = @{
        Success = $false
        Failure = $false
        Description = "Central access policy staging. Usually disabled."
        MITRE = "N/A"
    }
    "Detailed File Share" = @{
        Success = $true
        Failure = $true
        Description = "Detailed file share access with file names. Volume consideration."
        MITRE = "T1039"
    }
    "File Share" = @{
        Success = $true
        Failure = $true
        Description = "File share connection events. Critical for lateral movement."
        MITRE = "T1021.002"
    }
    "File System" = @{
        Success = $true
        Failure = $true
        Description = "File system access. Requires SACL configuration."
        MITRE = "T1083, T1005"
    }
    "Filtering Platform Connection" = @{
        Success = $true
        Failure = $true
        Description = "Windows Filtering Platform connections."
        MITRE = "T1071"
    }
    "Filtering Platform Packet Drop" = @{
        Success = $false
        Failure = $true
        Description = "Dropped packets. High volume, enable selectively."
        MITRE = "T1562.004"
    }
    "Handle Manipulation" = @{
        Success = $false
        Failure = $false
        Description = "Handle duplication. Very high volume, usually disabled."
        MITRE = "T1055"
    }
    "Kernel Object" = @{
        Success = $true
        Failure = $true
        Description = "Kernel object access for rootkit detection."
        MITRE = "T1014"
    }
    "Other Object Access Events" = @{
        Success = $true
        Failure = $true
        Description = "Catch-all for object access."
        MITRE = "T1083"
    }
    "Registry" = @{
        Success = $true
        Failure = $true
        Description = "Registry access. Requires SACL configuration."
        MITRE = "T1012, T1112"
    }
    "Removable Storage" = @{
        Success = $true
        Failure = $true
        Description = "Removable media access for data exfiltration detection."
        MITRE = "T1052.001"
    }
    "SAM" = @{
        Success = $true
        Failure = $true
        Description = "SAM database access. Critical for credential dumping detection."
        MITRE = "T1003.002"
    }

    # ==========================================================================
    # POLICY CHANGE CATEGORY
    # Security policy modifications
    # MITRE: T1484 (Domain Policy Modification)
    # ==========================================================================
    "Audit Policy Change" = @{
        Success = $true
        Failure = $true
        Description = "CRITICAL: Detects audit policy tampering."
        MITRE = "T1562.002"
    }
    "Authentication Policy Change" = @{
        Success = $true
        Failure = $true
        Description = "Authentication policy changes."
        MITRE = "T1484"
    }
    "Authorization Policy Change" = @{
        Success = $true
        Failure = $true
        Description = "Authorization policy changes."
        MITRE = "T1484"
    }
    "Filtering Platform Policy Change" = @{
        Success = $true
        Failure = $false
        Description = "WFP policy changes."
        MITRE = "T1562.004"
    }
    "MPSSVC Rule-Level Policy Change" = @{
        Success = $true
        Failure = $true
        Description = "Windows Firewall rule changes."
        MITRE = "T1562.004"
    }
    "Other Policy Change Events" = @{
        Success = $true
        Failure = $true
        Description = "Catch-all for policy changes."
        MITRE = "T1484"
    }

    # ==========================================================================
    # PRIVILEGE USE CATEGORY
    # Sensitive privilege usage monitoring
    # MITRE: T1134 (Access Token Manipulation)
    # ==========================================================================
    "Non Sensitive Privilege Use" = @{
        Success = $false
        Failure = $false
        Description = "Non-sensitive privileges. Usually disabled for volume."
        MITRE = "T1134"
    }
    "Other Privilege Use Events" = @{
        Success = $true
        Failure = $true
        Description = "Catch-all for privilege use."
        MITRE = "T1134"
    }
    "Sensitive Privilege Use" = @{
        Success = $true
        Failure = $true
        Description = "CRITICAL: SeDebug, SeTcb, SeBackup privilege usage."
        MITRE = "T1134, T1003"
    }

    # ==========================================================================
    # SYSTEM CATEGORY
    # System-level events
    # MITRE: T1562 (Impair Defenses)
    # ==========================================================================
    "IPsec Driver" = @{
        Success = $true
        Failure = $true
        Description = "IPsec driver events."
        MITRE = "T1071"
    }
    "Other System Events" = @{
        Success = $true
        Failure = $true
        Description = "Catch-all for system events."
        MITRE = "T1082"
    }
    "Security State Change" = @{
        Success = $true
        Failure = $true
        Description = "System security state changes."
        MITRE = "T1562"
    }
    "Security System Extension" = @{
        Success = $true
        Failure = $true
        Description = "Security subsystem extensions (authentication packages)."
        MITRE = "T1547.002"
    }
    "System Integrity" = @{
        Success = $true
        Failure = $true
        Description = "System integrity violations."
        MITRE = "T1562"
    }
}

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

function Write-Log {
    param(
        [Parameter(Mandatory)]
        [string]$Message,

        [ValidateSet("Info", "Warning", "Error", "Success")]
        [string]$Level = "Info"
    )

    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $color = switch ($Level) {
        "Info"    { "White" }
        "Warning" { "Yellow" }
        "Error"   { "Red" }
        "Success" { "Green" }
    }

    $logMessage = "[$timestamp] [$Level] $Message"
    Write-Host $logMessage -ForegroundColor $color

    if ($LogPath) {
        $logFile = Join-Path $LogPath "AuditPolicy_$(Get-Date -Format 'yyyyMMdd').log"
        Add-Content -Path $logFile -Value $logMessage -ErrorAction SilentlyContinue
    }
}

function Test-AdminPrivilege {
    $currentPrincipal = New-Object Security.Principal.WindowsPrincipal(
        [Security.Principal.WindowsIdentity]::GetCurrent()
    )
    return $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Backup-AuditPolicy {
    param([string]$BackupPath)

    try {
        $backupFile = Join-Path $BackupPath "AuditPolicy_Backup_$(Get-Date -Format 'yyyyMMdd_HHmmss').csv"
        Write-Log "Creating audit policy backup: $backupFile" -Level Info

        $result = auditpol /backup /file:$backupFile 2>&1
        if ($LASTEXITCODE -ne 0) {
            throw "auditpol backup failed: $result"
        }

        Write-Log "Backup created successfully" -Level Success
        return $backupFile
    }
    catch {
        Write-Log "Failed to create backup: $_" -Level Error
        throw
    }
}

function Get-CurrentAuditPolicy {
    param([string]$Subcategory)

    # Get the GUID for this subcategory (language-independent)
    $guid = $Script:SubcategoryGUIDs[$Subcategory]
    if (-not $guid) {
        return $null
    }

    $output = auditpol /get /subcategory:$guid /r 2>&1
    if ($LASTEXITCODE -ne 0) {
        return $null
    }

    # Parse CSV output
    $lines = $output -split "`n" | Where-Object { $_ -match "," }
    if ($lines.Count -ge 2) {
        $settings = $lines[1] -split ","
        return @{
            Subcategory = $settings[2]
            InclusionSetting = $settings[4]
        }
    }
    return $null
}

function Set-AuditPolicySubcategory {
    param(
        [Parameter(Mandatory)]
        [string]$Subcategory,

        [bool]$Success = $false,

        [bool]$Failure = $false
    )

    # Get the GUID for this subcategory (language-independent)
    $guid = $Script:SubcategoryGUIDs[$Subcategory]
    if (-not $guid) {
        throw "Unknown subcategory '$Subcategory' - no GUID mapping found"
    }

    # Build auditpol command using GUID (works on all Windows languages)
    $args = @("/set", "/subcategory:$guid")

    if ($Success -and $Failure) {
        $args += "/success:enable", "/failure:enable"
    }
    elseif ($Success) {
        $args += "/success:enable", "/failure:disable"
    }
    elseif ($Failure) {
        $args += "/success:disable", "/failure:enable"
    }
    else {
        $args += "/success:disable", "/failure:disable"
    }

    if ($PSCmdlet.ShouldProcess($Subcategory, "Set audit policy")) {
        $result = & auditpol $args 2>&1
        if ($LASTEXITCODE -ne 0) {
            throw "Failed to set audit policy for '$Subcategory' ($guid): $result"
        }
        return $true
    }
    return $false
}

function Enable-CommandLineAuditing {
    <#
    .SYNOPSIS
        Enables command line auditing in process creation events.
    .DESCRIPTION
        Configures the registry to include command line arguments in
        Event ID 4688 (Process Creation). CRITICAL for detection.
    #>

    $regPath = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit"
    $regName = "ProcessCreationIncludeCmdLine_Enabled"

    try {
        if (-not (Test-Path $regPath)) {
            New-Item -Path $regPath -Force | Out-Null
        }

        if ($PSCmdlet.ShouldProcess("Command Line Auditing", "Enable")) {
            Set-ItemProperty -Path $regPath -Name $regName -Value 1 -Type DWord
            Write-Log "Command line auditing enabled (ProcessCreationIncludeCmdLine_Enabled = 1)" -Level Success
        }
    }
    catch {
        Write-Log "Failed to enable command line auditing: $_" -Level Error
        throw
    }
}

function Configure-EventLogSettings {
    <#
    .SYNOPSIS
        Configures event log sizes and retention settings.
    .DESCRIPTION
        Sets appropriate log sizes to prevent event loss.
        Recommended minimums based on event volume analysis.
    #>

    $logSettings = @{
        "Security" = @{
            MaxSizeKB = 4194240  # 4GB - Critical for forensics
            RetentionDays = 90
        }
        "System" = @{
            MaxSizeKB = 1048576  # 1GB
            RetentionDays = 90
        }
        "Application" = @{
            MaxSizeKB = 1048576  # 1GB
            RetentionDays = 90
        }
        "Microsoft-Windows-PowerShell/Operational" = @{
            MaxSizeKB = 1048576  # 1GB - PowerShell logging
            RetentionDays = 90
        }
        "Microsoft-Windows-Sysmon/Operational" = @{
            MaxSizeKB = 2097152  # 2GB - Sysmon generates volume
            RetentionDays = 90
        }
        "Microsoft-Windows-WMI-Activity/Operational" = @{
            MaxSizeKB = 262144   # 256MB
            RetentionDays = 90
        }
        "Microsoft-Windows-TaskScheduler/Operational" = @{
            MaxSizeKB = 262144   # 256MB
            RetentionDays = 90
        }
    }

    foreach ($logName in $logSettings.Keys) {
        try {
            $config = $logSettings[$logName]

            if ($PSCmdlet.ShouldProcess($logName, "Configure event log")) {
                # Try wevtutil first
                $result = wevtutil sl $logName /ms:$($config.MaxSizeKB * 1024) 2>&1

                if ($LASTEXITCODE -eq 0) {
                    Write-Log "Configured $logName : MaxSize=$($config.MaxSizeKB)KB" -Level Success
                }
                else {
                    Write-Log "Could not configure $logName (may not exist): $result" -Level Warning
                }
            }
        }
        catch {
            Write-Log "Failed to configure $logName : $_" -Level Warning
        }
    }
}

function Restore-DefaultAuditPolicy {
    <#
    .SYNOPSIS
        Restores audit policy to Windows defaults.
    #>

    Write-Log "Restoring default audit policy..." -Level Warning

    if ($PSCmdlet.ShouldProcess("All audit policies", "Restore defaults")) {
        $result = auditpol /clear /y 2>&1
        if ($LASTEXITCODE -ne 0) {
            throw "Failed to restore defaults: $result"
        }
        Write-Log "Audit policy restored to defaults" -Level Success
    }
}

# ============================================================================
# MAIN EXECUTION
# ============================================================================

function Main {
    Write-Log "============================================" -Level Info
    Write-Log "Windows Audit Policy Configuration Script" -Level Info
    Write-Log "Version 2.1.0 (Multi-Language Support)" -Level Info
    Write-Log "============================================" -Level Info

    # Verify admin privileges
    if (-not (Test-AdminPrivilege)) {
        Write-Log "This script requires administrative privileges." -Level Error
        throw "Administrative privileges required"
    }

    # Create log directory
    if (-not (Test-Path $LogPath)) {
        New-Item -Path $LogPath -ItemType Directory -Force | Out-Null
        Write-Log "Created log directory: $LogPath" -Level Info
    }

    # Handle restore defaults
    if ($RestoreDefaults) {
        Restore-DefaultAuditPolicy
        return
    }

    # Backup existing policy
    if ($BackupExisting) {
        $backupFile = Backup-AuditPolicy -BackupPath $LogPath
        Write-Log "Backup saved to: $backupFile" -Level Info
    }

    # Get OS version for DC-specific policies
    $isDomainController = (Get-WmiObject -Class Win32_ComputerSystem).DomainRole -ge 4
    Write-Log "System Role: $(if ($isDomainController) { 'Domain Controller' } else { 'Member Server/Workstation' })" -Level Info

    # Apply audit policies
    $successCount = 0
    $failCount = 0

    foreach ($policy in $Script:AuditPolicies.GetEnumerator()) {
        $subcategory = $policy.Name
        $config = $policy.Value

        # Skip DS Access on non-DCs
        if ($subcategory -match "Directory Service" -and -not $isDomainController) {
            Write-Log "Skipping '$subcategory' (not a Domain Controller)" -Level Info
            continue
        }

        # Skip Process Creation/Termination if Sysmon is installed (avoids duplicates)
        # Sysmon Event 1/5 are superior to Windows Event 4688/4689
        if ($SysmonInstalled -and $config.ContainsKey('SkipIfSysmon') -and $config.SkipIfSysmon) {
            Write-Log "Skipping '$subcategory' (Sysmon installed - use Sysmon Event instead)" -Level Info
            continue
        }

        try {
            Write-Log "Configuring: $subcategory (Success: $($config.Success), Failure: $($config.Failure))" -Level Info

            if (Set-AuditPolicySubcategory -Subcategory $subcategory -Success $config.Success -Failure $config.Failure) {
                $successCount++
            }
        }
        catch {
            Write-Log "Failed to configure '$subcategory': $_" -Level Error
            $failCount++
        }
    }

    # Enable command line auditing
    Write-Log "Enabling command line auditing..." -Level Info
    Enable-CommandLineAuditing

    # Configure event log settings
    Write-Log "Configuring event log sizes..." -Level Info
    Configure-EventLogSettings

    # Summary
    Write-Log "============================================" -Level Info
    Write-Log "Configuration Complete" -Level Success
    Write-Log "Policies configured successfully: $successCount" -Level Info
    Write-Log "Policies failed: $failCount" -Level $(if ($failCount -gt 0) { "Warning" } else { "Info" })
    Write-Log "============================================" -Level Info

    # Verify configuration
    Write-Log "Verifying configuration..." -Level Info
    $verification = auditpol /get /category:* /r 2>&1
    $verifyFile = Join-Path $LogPath "AuditPolicy_Applied_$(Get-Date -Format 'yyyyMMdd_HHmmss').csv"
    $verification | Out-File -FilePath $verifyFile -Encoding UTF8
    Write-Log "Current policy exported to: $verifyFile" -Level Info

    if ($failCount -gt 0) {
        Write-Log "WARNING: Some policies failed to apply. Review the log for details." -Level Warning
        exit 1
    }
}

# Run main function
Main
